const PARACHUTIST_DRAG_COEFFICIENT = 0.7;
const PARACHUTE_DRAG_COEFFICIENT = 1.225;
const GRAVITY = 9.8;
const AIR_DENSITY = 1.2041;

const MIN_HEIGHT = 3000;
const MAX_HEIGHT = 10000;

export {
  MAX_HEIGHT,
  MIN_HEIGHT,
  AIR_DENSITY,
  GRAVITY,
  PARACHUTE_DRAG_COEFFICIENT,
  PARACHUTIST_DRAG_COEFFICIENT
};
